.

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -19,6 +19,21 @@ jobs:
           docker compose -f docker-compose.yaml -f docker-compose.tests.yaml up -d --build
           docker compose ps
 
+      - name: Wait Django app is ready
+        run: |
+          cd docker
+          for i in {1..15}; do
+            echo "Checking if Django is up ($i/15)..."
+            if curl -s --fail http://localhost > /dev/null; then
+              echo "Django is ready!"
+              exit 0
+            fi
+            echo "Django is not ready yet..."
+            sleep 2
+          done
+          echo "Django failed to start in time." >&2
+          docker compose logs web
+          exit 1
 
       - name: Run tests
         run: |
